from typing import List
from src.storage.connection import DatabaseConnection
from src.storage.models import ClusterDB, ArticleDB
from src.agents.state import NewsCluster
from src.utils.logger import project_logger as logger

class ClusterRepository:
    """Data Access Object for persisting processed news clusters."""
    
    def __init__(self, db_connection: DatabaseConnection):
        """
        Args:
            db_connection: Initialized connection manager.
        """
        self.db = db_connection

    def save_clusters(self, clusters: List[NewsCluster]):
        """
        Maps agent state clusters to database models and persists them.
        
        Args:
            clusters: List of clusters generated by the pipeline.
        """
        if not clusters:
            return

        with self.db.get_session() as session:
            try:
                for cluster in clusters:
                    # 1. Map Cluster
                    db_cluster = ClusterDB(
                        cluster_id=cluster.cluster_id,
                        main_event=cluster.main_event,
                        summary_3_bullets=cluster.summary_3_bullets,
                        overall_bias=cluster.overall_bias,
                        reasoning_trace=cluster.reasoning_trace,
                        is_blindspot=cluster.is_blindspot
                    )
                    
                    # 2. Map associated articles
                    db_cluster.articles = [
                        ArticleDB(
                            title=a.title,
                            link=a.link,
                            source=a.source,
                            summary=a.summary,
                            full_text=a.full_text,
                            published_at=a.published_at,
                            bias_score=a.bias_score
                        ) for a in cluster.articles
                    ]
                    
                    session.add(db_cluster)
                
                session.commit()
                logger.success(f"Saved {len(clusters)} clusters to database.")
            except Exception as e:
                session.rollback()
                logger.error(f"Persistence Failed: {str(e)}")
                raise e
